name: CI
on:
  push:
    branches:
      - hexo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 切换分支
        uses: actions/checkout@v2

      - name: 安装依赖
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: 清除Hexo
        uses: heowc/action-hexo@main
        with:
          args: clean

      - name: 生成Hexo
        uses: heowc/action-hexo@main
        with:
          args: generate

      - name: 部署到master分支
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.CI_TOKEN }}
          external_repository: hugh-zhan9/hugh-zhan9.github.io
          publish_branch: master
          publish_dir: ./public

      - name: 部署到个人服务器
        env:
          ACTION_DEPLOY_KEY: -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEA1azkCMhqnVH7e6w6xu1Ey5UwCb9sTN0CqIVygpifZ1DQTGac2zMj
VkkG5wv1tcYGoF9Z6AY2ri2YScwpGXKG6Po3Ff2DeDxbpFdgFHswEDtmFmGlW7SAwjqPCQ
gjAPPrRknAYNWn563EvM1+uGVmFQoOpGZwFl2NbY+nOOlJonj4U5jwC6xLSusEDKqmL23O
0t4j+PZTm4TbqB/bpjv3/0cMsc5rsacCwT/2pdsL8d9YhDZdOU+goHz83mHF8rlpG9A+53
V2v++LgYcz4kHHAEnIos0XgAldlIQg30cpKUdQUD0A7KpuT66Yel2Favj5wPNRXMbPdLnc
07ZFQRrr6QcQ8DNMfuLAIi0loF54LtvTzjL5F8T4EzNdrhzupBX5hLK8VaIsfWFi8Vqqhc
coBXkkGDPx4nF/8VhB66PdOnxIqPmRoa0v/5iD4g2xlLmBUGffUtQuYLfHDi16TDyzeq5m
WYWyUaAzHo5JpMqcR3aztp3Ic07Xx4NDylDIs+EKCavhJb+4eR/SOmnPtQyR+SPQ6L7uec
uKfZB7JT21nl37xGwbUzv9gbyZ/KqwYaoPDu83tvEsa+Hgz7BugjcP/lZ5acku452IlCji
4CBNHD9lfNsZMkpnUnqzS7C50bJxPyWu9sr88ruXlqso0rlp9m1yGGcAyo5TMq9OqQreun
0AAAdIx8fcPsfH3D4AAAAHc3NoLXJzYQAAAgEA1azkCMhqnVH7e6w6xu1Ey5UwCb9sTN0C
qIVygpifZ1DQTGac2zMjVkkG5wv1tcYGoF9Z6AY2ri2YScwpGXKG6Po3Ff2DeDxbpFdgFH
swEDtmFmGlW7SAwjqPCQgjAPPrRknAYNWn563EvM1+uGVmFQoOpGZwFl2NbY+nOOlJonj4
U5jwC6xLSusEDKqmL23O0t4j+PZTm4TbqB/bpjv3/0cMsc5rsacCwT/2pdsL8d9YhDZdOU
+goHz83mHF8rlpG9A+53V2v++LgYcz4kHHAEnIos0XgAldlIQg30cpKUdQUD0A7KpuT66Y
el2Favj5wPNRXMbPdLnc07ZFQRrr6QcQ8DNMfuLAIi0loF54LtvTzjL5F8T4EzNdrhzupB
X5hLK8VaIsfWFi8VqqhccoBXkkGDPx4nF/8VhB66PdOnxIqPmRoa0v/5iD4g2xlLmBUGff
UtQuYLfHDi16TDyzeq5mWYWyUaAzHo5JpMqcR3aztp3Ic07Xx4NDylDIs+EKCavhJb+4eR
/SOmnPtQyR+SPQ6L7uecuKfZB7JT21nl37xGwbUzv9gbyZ/KqwYaoPDu83tvEsa+Hgz7Bu
gjcP/lZ5acku452IlCji4CBNHD9lfNsZMkpnUnqzS7C50bJxPyWu9sr88ruXlqso0rlp9m
1yGGcAyo5TMq9OqQreun0AAAADAQABAAACAE8ypNbIihPDhkXhoWuIGB6pLkP+qoKWzFxw
EfBr53Fg18PpqKvqeWeK678JhMoaGuyoSuegHfZTOgXoYTdoZq7Fx1MkQu122bTBGgCdZE
Qv7/fNu3+RGMRk9g0v8eFxhzvnLCH4LyLFGo2sURLBqqOTtbejrFnt1PTN8Po8JanN0qUR
o69/7exXzYlwWuZreeRYp9aoXnbfOJdJL52ezp3U1NS2oN4Y/AFq1t3EodnFocZnbAhJBk
1V5lf6v2bm6BmCBz69IAWmIPwig82R+dOWhYIqKFKxpfjdPF3lv1DoeNE0uzn9NaPdH/EC
5ueuXsvwo7CSk+Q826exAFxQQS3Rgi618lF++UdBWXbKk/NFUldaxQJKczfDM+kIy2MmZc
gkeDgngvzLgT7tmo9JAeijh4/KVKoezMB6IO0ALrR/Pr2NEL9ndXTTxQisWdGmm46xQ2v0
dq0S0YNEDArTInNfPBUtAihzvH121yRrqTVYp7/SioORy6bRaU7VytL/iA9Y58Z7HlpVcL
MV0SpR5n1A9VV1j4FmneTw0qqzYwGUhbWYXXCbyx0JuzwgoxmzmL0/yhdLCzbZeTor7tQP
2FX8wZyjMDt9mTc/9Fumx8+g4QTX5hpZQDmGaz74yXVTOCWqrwDMPZ+bNHCqVCyGtn8IZj
a7KuFgwLkOPewnYFUhAAABAQCdAtirreopErrTDRAh1jkdxQmJ/kr5tplS51HeJsCkLDF9
kLyrY7A4QsRqNwucYtn8t+X85ZTCiQmt2Gys8JY2Z2FwBHlpL+24e1HaDONS4EYtdkhsYU
SpcR/b8VD5qcgpDfBd87o4PCVeXR7bCoj4WRFmAKsgJyZDVxFzDPpVXNWY9DGpDAkJbff+
cdEdjEwuyOhPS0qshtzSoIS8UM4rxq433b5xhgU/7T+R1VUPT5yw5nhd6fO0d91tF52jy8
1t2MPTjyaT6/Xa83tVs5BvrivDsBxt+yKyqwkY3z4Nu+x9xoB+9B/phpa5VwDQ32lD1kPx
Kn9vUBnrWzwrTqV5AAABAQD0Im4yQfRGDTC/UO18R8PTAOTh0DIfm/P2y0l8WDHvX8OYUU
BtzIf7enj50T72Os2lC0Gm23GnixbulO/WR6EbPYOsIIPHggD/O0TcsMVQW9euRnPo0uZT
SlQ4Fc+czCsF/BJVsneRratz/H5tSD15+OiwGOu0DgONzff9OH8W4C07UHaYrBMfa8qcnW
Q07oUn7H/EiYlzaDWU5wxRwnrz/PySjuPafpmfFTbbxCHR0tudhV4xxy9TV6yOG6qNQHWn
tOiTBxSBxo6A0zAy/zx36ShOCjwXCP0cN9D4YfFya48Dj9SNHSQugOo8m7kqf72RNJ8Ztj
ZtQAIZN4GRjpwZAAABAQDgD3tPfghLtcaPjuinCX/mCgMYDmbTpCngXuBjdSzcIjIOaSMZ
AP1OvkHnh8/uecH/ygOwtv7mnO9Vb9M6K2mo16pY78dW05rTJMGOmrWgzM4HUfkxqoZL11
QKqtMdiOCfnvUm4TiPXBfKViMD6OaRRjUsweBxtItSfFJMjEm3VyiSraFjzo0v84PkzQ6H
71eI6CWgDiwxfBZxQoKlrfjU1dtgqBxHf83lbYaAqKDbuAixvpTZdpsSoRXXxYQdUAlJpr
e7NdRA0NH+OzeKM8PYC8R0J9dm/hAp+uPt7c+9MrYZnsaPtvsXGvQmwF9+18gggieEI8d9
MbvGEEy8eN4FAAAAEmh1Z2hfemhhbjlAMTYzLmNvbQ==
-----END OPENSSH PRIVATE KEY-----
          SERVER_DIR: ${{ secrets.SERVER_DIR }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          mv ./public ./www
          scp -o StrictHostKeyChecking=no -r ./www $SERVER_DIR
